### PR TITLE
What if my users want 'dislike' feature.

### PR DESCRIPTION
**Pull request by amrnt**
Add plusminus and cancel_like! methods.
Needs refactoring, tests and implementing facepile for unlike.

### CODE REVIEW

**Comment by schneems** [comment]
I think this is a great idea, more flexibility, one library. Can we change 'unlike' to 'dislike' since the connotation of unlike is to only remove a like from an object, rather than to make it go negative? Would also like to see this in a separate module, so users can choose to include Likeable::Dislike in their classes or not, making the action explicit. 

We should also consider how liking and disliking an object affect one another. For instance if an object is liked (+1), and then disliked (-1) by the same person the user would expect the value to be (-1) rather than (0). So if the same user dislikes something they already liked, it should remove that like in addition to adding the dislike.

**Comment by amrnt** [comment]
Awesome! I'll push the changes in the next couple days and I'll try to include some tests.

**Comment by amrnt** [comment]
@schneems Is it okay to work and add the feature on `master` branch? or continue on a separate branch?

**Comment by schneems** [comment]
Either way is fine, the pull requests all go to master for me : )

**Comment by kirs** [comment]
Great feature. Thanks to @amrnt

**Comment by amrnt** [comment]
I will close this and open master to master pull request

**Comment by amrnt** [comment]
Here's the new one: https://github.com/gowalla/Likeable/pull/7

**Pull request closed without merging**
